lipunmyynti/urls.py
# encoding: utf-8
# vim: shiftwidth=4 expandtab

from django.conf.urls.defaults import *
from django.contrib import admin

import ticket_sales.urls
import payments.urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(payments.urls)),
    url(r'^', include(ticket_sales.urls)),
)

payments/urls.py
# encoding: utf-8
# vim: shiftwidth=4 expandtab

from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to

from payments.views import *

urlpatterns = patterns('',
    url(r'process/$', payment_view, name="payment_view")
)

ticket_sales/urls.py
# encoding: utf-8
# vim: shiftwidth=4 expandtab

from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to

from ticket_sales.views import *

urlpatterns = patterns('',
    url(r'tervetuloa/$', welcome_view, name="welcome_phase"),
    #url(r'tervetuloa/$', closed_view, name="closed_phase"),
    url(r'liput/$', tickets_view, name="tickets_phase"),
    url(r'toimitusosoite/$', address_view, name="address_phase"),
    url(r'vahvistus/$', confirm_view, name="confirm_phase"),
    url(r'kiitos/$', thanks_view, name="thanks_phase"),

    url(r'stats/$', redirect_to, dict(url='/hallinta/tiedot/'), name="old_stats_url"),

    url(r'hallinta/$', manage_view, name="manage_view"),
    url(r'hallinta/haku/$', search_view, name="search_view"),
    url(r'hallinta/tilaus/$', order_view, name="order_view"),

    url(r'hallinta/maksut/$', payments_view, name="payments_view"),
    url(r'hallinta/maksut/yksi/$', process_single_payment_view, name="process_single_payment_view"),
    url(r'hallinta/maksut/yksi/vahvista/$', confirm_single_payment_view, name="confirm_single_payment_view"),
    url(r'hallinta/maksut/monta/$', process_multiple_payments_view, name="process_multiple_payments_view"),
    url(r'hallinta/maksut/monta/vahvista/$', confirm_multiple_payments_view, name="confirm_multiple_payments_view"),
    url(r'hallinta/erat/uusi/$', create_batch_view, name="create_batch_view"),
    url(r'hallinta/erat/(?P<batch_id>\d+)/$', render_batch_view, name="render_batch_view"),
    url(r'hallinta/erat/(?P<batch_id>\d+)/peru/$', cancel_batch_view, name="cancel_batch_view"),
    url(r'hallinta/erat/(?P<batch_id>\d+)/vahvista/$', deliver_batch_view, name="deliver_batch_view"),

    url(r'hallinta/tiedot/$', stats_view, name="stats_view"),
    url(r'hallinta/tickets_by_date/$', tickets_by_date_view, {'raw': False}, name="tickets_by_date_view"),
    url(r'hallinta/tickets_by_date/raw/$', tickets_by_date_view, {'raw': True}, name="tickets_by_date_raw"),

    url(r'kirjaudu/$', 'django.contrib.auth.views.login', dict(template_name="ticket_admin/login.html"), name="login"),
    url(r'kirjaudu/ulos/$', 'django.contrib.auth.views.logout', dict(template_name="ticket_admin/logged_out.html"), name="logout"),

    url(r'$', welcome_view, name="welcome_phase"),
)

ticket_sales/models.py
# encoding: utf-8
# vim: shiftwidth=4 expandtab

from datetime import datetime, timedelta, date
from datetime import time as dtime
from time import time, mktime

from django.db import models, IntegrityError
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.conf import settings
from django.utils import timezone

from payments.utils import compute_payment_request_mac

from .format import format_date, format_datetime, format_price
from .receipt import render_receipt

__all__ = [
    "School",
    "Batch",
    "Product",
    "Customer",
    "Order",
    "OrderProduct",
    "SHIPPING_AND_HANDLING_CENTS",
]

SHIPPING_AND_HANDLING_CENTS = getattr(settings, 'SHIPPING_AND_HANDLING_CENTS', 0)
DUE_DAYS = getattr(settings, 'DUE_DAYS', 7)
LOW_AVAILABILITY_THRESHOLD = getattr(settings, 'LOW_AVAILABILITY_THRESHOLD', 10)
DEFAULT_FINAL_DEATH_DAYS = 14 # XXX no longer used

class Batch(models.Model):
    create_time = models.DateTimeField(auto_now=True)
    print_time = models.DateTimeField(null=True, blank=True)
    prepare_time = models.DateTimeField(null=True, blank=True)
    delivery_time = models.DateTimeField(null=True, blank=True)

    @property
    def is_printed(self):
        return self.print_time is not None

    @property
    def is_prepared(self):
        return self.prepare_time is not None

    @property
    def is_delivered(self):
        return self.delivery_time is not None

    @property
    def delivery_date(self):
        return self.delivery_time.date()

    @property
    def readable_state(self):
        if self.is_delivered:
            return u"Delivered at %s" % format_date(self.delivery_time)
        elif self.is_prepared:
            return u"Prepared at %s; awaiting delivery" % format_date(self.prepare_time)
        elif self.is_printed:
            return u"Printed at %s; awaiting preparation" % format_date(self.print_time)
        else:
            return u"Awaiting print"

    @classmethod
    def create(cls, max_orders=100):
        # XXX concurrency disaster waiting to happen
        # solution: only I do the botching^Wbatching

        batch = cls()
        batch.save()

        orders = Order.objects.filter(
            # Order is confirmed
            confirm_time__isnull=False,

            # Order is paid
            payment_date__isnull=False,

            # Order has not yet been allocated into a Batch
            batch__isnull=True,

            # Order has not been cancelled
            cancellation_time__isnull=True
        ).order_by("confirm_time")

        accepted = 0

        for order in orders:
            # TODO do this in the database
            # Some orders need not be shipped.
            if not order.requires_shipping:
                continue

            order.batch = batch
            order.save()

            accepted += 1
            if accepted >= max_orders:
                break

        return batch

    def render(self, c):
        for order in self.order_set.all():
            order.render(c)

    def cancel(self):
        for order in self.order_set.all():
            order.batch = None
            order.save()

        self.delete()

    def confirm_delivery(self, delivery_time=None):
        if delivery_time is None:
            delivery_time = timezone.now()

        self.delivery_time = delivery_time
        self.save()
        self.send_delivery_confirmation_messages()

    def send_delivery_confirmation_messages(self):
        for order in self.order_set.all():
            order.send_confirmation_message("toimitusvahvistus")

    def __unicode__(self):
        return u"#%d (%s)" % (
            self.pk,
            self.readable_state
        )

    class Meta:
        verbose_name_plural = "batches"

        permissions = (
            ("can_manage_batches", "Can manage batches"),
        )

class Product(models.Model):
    name = models.CharField(max_length=100)
    internal_description = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField()
    mail_description = models.TextField(null=True, blank=True)
    sell_limit = models.IntegerField()
    price_cents = models.IntegerField()
    requires_shipping = models.BooleanField(default=True)
    available = models.BooleanField(default=True)
    ilmoitus_mail = models.CharField(max_length=100, null=True, blank=True)
    ordering = models.IntegerField(default=0)

    class Meta:
        ordering = ('ordering', 'id')

    @property
    def formatted_price(self):
        return format_price(self.price_cents)
    
    @property
    def in_stock(self):
        return (self.amount_available > 0)

    @property
    def availability_low(self):
        return (self.amount_available < LOW_AVAILABILITY_THRESHOLD)

    @property
    def amount_available(self):
        return self.sell_limit - self.amount_sold

    @property
    def amount_sold(self):
        cnt = OrderProduct.objects.filter(product=self, order__confirm_time__isnull=False, order__cancellation_time__isnull=True).aggregate(models.Sum('count'))
        sm = cnt['count__sum']
        return sm if sm is not None else 0

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.formatted_price)

class School(models.Model):
    # REVERSE: order_set

    name = models.CharField(max_length=40)
    address = models.CharField(max_length=40)
    max_people = models.IntegerField()
    priority = models.IntegerField()

    @property
    def amount_placed(self):
        if self.id is None:
            return 0

        total = 0
        for order in self.order_set.filter(confirm_time__isnull=False, payment_date__isnull=False, cancellation_time__isnull=True):
            sleepy_op = order.order_product_set.get(product__name__icontains=u'majoitus')
            total += sleepy_op.count
        return total

    @property
    def amount_available(self):
        return self.max_people - self.amount_placed

    def __unicode__(self):
        return u"%s (%s/%s)" % (self.name, self.amount_placed, self.max_people)


class Customer(models.Model):
    # REVERSE: order = OneToOne(Order)
    first_name = models.CharField(max_length=100, verbose_name="Etunimi")
    last_name = models.CharField(max_length=100, verbose_name="Sukunimi")
    email = models.EmailField(verbose_name="Sähköpostiosoite")
    address = models.CharField(max_length=200, verbose_name="Katuosoite")
    zip_code = models.CharField(max_length=5, verbose_name="Postinumero")
    city = models.CharField(max_length=30, verbose_name="Postitoimipaikka")
    phone_number = models.CharField(max_length=30, null=True, blank=True, verbose_name="Puhelinnumero")

    def __unicode__(self):
        return self.name

    @property

    def name(self):
        return u"%s %s" % (self.first_name, self.last_name)

    @property
    def sanitized_name(self):
        return u"".join(i for i in self.name if i.isalpha() or i in
            (u'ä', u'Ä', u'ö', u'Ö', u'å', u'Å', u'-', u"'", u" "))

    @property
    def name_and_email(self):
        return u"%s <%s>" % (self.sanitized_name, self.email)

class Order(models.Model):
    # REVERSE: order_product_set = ForeignKeyFrom(OrderProduct)

    customer = models.OneToOneField(Customer, null=True, blank=True)
    start_time = models.DateTimeField(auto_now=True)
    confirm_time = models.DateTimeField(null=True, blank=True)
    ip_address = models.CharField(max_length=15, null=True, blank=True)
    payment_date = models.DateField(null=True, blank=True)
    cancellation_time = models.DateTimeField(null=True, blank=True)
    batch = models.ForeignKey(Batch, null=True, blank=True)
    school = models.ForeignKey(School, null=True, blank=True)

    @property
    def is_active(self):
        return self.is_confirmed and not self.is_cancelled

    @property
    def is_outstanding(self):
        return self.is_confirmed and self.requires_shipping and not self.is_cancelled

    @property
    def is_confirmed(self):
        return self.confirm_time is not None

    @property
    def is_paid(self):
        return self.payment_date is not None

    @property
    def is_batched(self):
        return self.batch is not None

    @property
    def is_delivered(self):
        return self.is_batched and self.batch.is_delivered

    @property
    def is_overdue(self):
        return self.is_confirmed and not self.is_paid and self.due_date < timezone.now()

    @property
    def is_cancelled(self):
        return self.cancellation_time is not None

    @property
    def price_cents(self):
        # TODO Port to Django DB reduction functions if possible
        return sum(op.price_cents for op in self.order_product_set.all()) + self.shipping_and_handling_cents

    @property
    def shipping_and_handling_cents(self):
        return SHIPPING_AND_HANDLING_CENTS if self.requires_shipping else 0

    @property
    def formatted_shipping_and_handling(self):
        return format_price(self.shipping_and_handling_cents)

    @property
    def requires_shipping(self):
        # TODO do this in the database, too
        #return any(op.product.requires_shipping for op in self.order_product_set.filter(count__gt=0))

        # XXX PURKKA: tuote id:lla 8 on se viallinen Amuri-tuote johon unohtui toimitusbitti paalle
        return any((op.product.requires_shipping and op.product.id != 8) for op in self.order_product_set.filter(count__gt=0))
    
    @property
    def formatted_price(self):
        return format_price(self.price_cents)

    @property
    def readable_state(self):
        if self.is_batched:
            return "Allocated into batch %d (%s)" % (self.batch.id, self.batch.readable_state)
        elif self.is_paid:
            return "Paid; awaiting allocation into batch"
        elif self.is_confirmed:
            if self.is_overdue:
                return "Confirmed; payment overdue since %s" % self.formatted_due_date
            else:

ticket_sales/forms.py
# encoding: utf-8
# vim: shiftwidth=4 expandtab

from django import forms
from django.contrib.localflavor.fi.forms import FIZipCodeField

from crispy_forms.helper import FormHelper

from ticket_sales.models import *

__all__ = [
    "NullForm",
    "OrderProductForm",
    "CustomerForm",
    "SinglePaymentForm",
    "ConfirmSinglePaymentForm",
    "MultiplePaymentsForm",
    "CreateBatchForm",
    "SearchForm",
]

class HappyIntegerField(forms.IntegerField):
    def __init__(self, size=2):
        max_value = 10 ** size - 1

        super(HappyIntegerField, self).__init__(
            widget=forms.TextInput(attrs=dict(size=2, maxlength=size)),
            min_value=0,
            max_value=max_value
        )

    def clean(self, value):
        if not value:
            return 0

        else:
            return super(HappyIntegerField, self).clean(value)

class NullForm(forms.Form):
    pass

class OrderProductForm(forms.ModelForm):
    count = HappyIntegerField(2)

    class Meta:
        exclude = ("order", "product")
        model = OrderProduct
        
class CustomerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

    class Meta:
        model = Customer

class SinglePaymentForm(forms.Form):
    ref_number = forms.CharField(max_length=19, label=u"Viitenumero")

class ConfirmSinglePaymentForm(forms.Form):
    order_id = forms.IntegerField()

class MultiplePaymentsForm(forms.Form):
    dump = forms.CharField(widget=forms.Textarea(attrs={'rows':15,'cols':'90'}), label=u"Pastee tähän")

class CreateBatchForm(forms.Form):
    max_orders = forms.IntegerField(label=u"Kuinka monta tilausta (enintään)?")

class SearchForm(forms.Form):
    id = forms.IntegerField(label=u"Tilausnumero", required=False)
    first_name = forms.CharField(label=u"Etunimi", required=False)
    last_name = forms.CharField(label=u"Sukunimi", required=False)
    email = forms.CharField(label=u"Sähköpostiosoite", required=False)

ticket_sales/templates/ticket_sales/address.html
{% extends "base/base.html" %}
{% load wizard_ui %}
{% comment %}
encoding: utf-8
vim: shiftwidth=2 expandtab
{% endcomment %}
{% block body_text %}
<h1>Toimitusosoite</h1>
{% endblock body_text %}
{% block form_content %}
<fieldset>
<p>Tarvitsemme vielä osoitteen, johon lähetämme tilaamasi Tracon-lippupaketit. Tilausvahvistuksen ja maksuohjeet saat sähköpostitse. Puhelinnumeroa käytämme, mikäli ongelmia syntyy. Emme luovuta yhteystietojasi eteenpäin.</p>
<p>Tähdellä merkityt kentät ovat pakollisia.</p>
<div id="address_container">
<div class="req addrfirst"><label for="id_first_name">Etunimi <strong>*</strong></label>{{ form.first_name }}</div>
<div class="req addrlast"><label for="id_last_name">Sukunimi <strong>*</strong></label>{{ form.last_name }}</div>
<div class="req addrfirst"><label for="id_address">Osoite <strong>*</strong></label>{{ form.address }}</div>
<div class="req addr"><label for="id_zip_code">Postinumero <strong>*</strong></label>{{ form.zip_code }}</div>
<div class="req addrlast"><label for="id_city">Postitoimipaikka <strong>*</strong></label>{{ form.city }}</div>
<div class="req"><label for="id_email">Sähköpostiosoite <strong>*</strong></label>{{ form.email }}</div>
<div class="opt last"><label for="id_phone_number">Puhelinnumero</label>{{ form.phone_number }}</div>
</div>
</fieldset>
{% endblock form_content %}
{% block mascot_text %}
{% endblock mascot_text %}

ticket_sales/templates/ticket_sales/checkout.html
{% comment %}
vim: shiftwidth=2 expandtab
encoding: utf-8
{% endcomment %}
<input type='hidden' name='VERSION' value='{{ CHECKOUT_PARAMS.VERSION }}'>
<input type='hidden' name='STAMP' value='{{ order.checkout_stamp }}'>
<input type='hidden' name='AMOUNT' value='{{ order.price_cents }}'>
<input type='hidden' name='REFERENCE' value='{{ order.reference_number }}'>
<input type='hidden' name='MESSAGE' value='{{ order.checkout_message }}'>
<input type='hidden' name='LANGUAGE' value='{{ CHECKOUT_PARAMS.LANGUAGE }}'>
<input type='hidden' name='MERCHANT' value='{{ CHECKOUT_PARAMS.MERCHANT }}'>
<input type='hidden' name='RETURN' value='{{ CHECKOUT_PARAMS.RETURN }}'>
<input type='hidden' name='CANCEL' value=''>
<input type='hidden' name='REJECT' value=''>
<input type='hidden' name='DELAYED' value=''>
<input type='hidden' name='COUNTRY' value='{{ CHECKOUT_PARAMS.COUNTRY }}'>
<input type='hidden' name='CURRENCY' value='{{ CHECKOUT_PARAMS.CURRENCY }}'>
<input type='hidden' name='DEVICE' value='{{ CHECKOUT_PARAMS.DEVICE }}'>
<input type='hidden' name='CONTENT' value='{{ CHECKOUT_PARAMS.CONTENT }}'>
<input type='hidden' name='TYPE' value='{{ CHECKOUT_PARAMS.TYPE }}'>
<input type='hidden' name='ALGORITHM' value='{{ CHECKOUT_PARAMS.ALGORITHM }}'>
<input type='hidden' name='DELIVERY_DATE' value='{{ CHECKOUT_PARAMS.DELIVERY_DATE }}'>
<input type='hidden' name='FIRSTNAME' value='{{ order.customer.first_name }}'>
<input type='hidden' name='FAMILYNAME' value='{{ order.customer.last_name }}'>
<input type='hidden' name='ADDRESS' value='{{ order.customer.address }}'>
<input type='hidden' name='POSTCODE' value='{{ order.customer.zip_code }}'>
<input type='hidden' name='POSTOFFICE' value='{{ order.customer.city}}'>
<input type='hidden' name='MAC' value='{{ order.checkout_mac }}'>

ticket_sales/templates/ticket_sales/closed.html
{% extends "base/base.html" %}
{% load wizard_ui %}
{% comment %}
encoding: utf-8
vim: shiftwidth=2 expandtab
{% endcomment %}
{% block body_text %}
<h1>Lippukauppa on suljettu</h1>
{% endblock %}
{% block mascot_text %}
<p>Lippuja myydään myös ovella!</p>
{% endblock %}
{% block form_content %}
<p class="welcome">Ennakkolippujen myynti on tältä erää lopetettu.</p>
<p class="welcome">Lisätietoja lipuista voit lukea <a href="http://2012.tracon.fi/liput" target="_blank">tapahtuman kotisivuilta.</a></p>
{% endblock %}

ticket_sales/templates/ticket_sales/confirm.html
{% extends "base/base.html" %}
{% load wizard_ui %}
{% comment %}
encoding: utf-8
vim: shiftwidth=2 expandtab
{% endcomment %}
{% block body_text %}
<h1>Vahvista tilaus</h1>
{% endblock body_text %}
{% block form_content %}
<p>Tarkista vielä tilauksen tietosi ja tilaamiesi tuotteiden määrät. Tuotteet maksetaan tilisiirrolla. Tilauksilla on maksuaikaa <strong>7 päivää tilauksesta.</strong></p>
{% include "ticket_sales/order_statement.html" %}
{% include "ticket_sales/checkout.html" %}
{% endblock form_content %}

ticket_sales/templates/ticket_sales/generic_buttons.html
{% comment %}
  Implementation of navigation buttons.
{% endcomment %}

{% if phase.next_phase %}
  {% comment %}
    This button is removed from view using CSS.
  {% endcomment %}
  <button class="enterhack buttongradient" type="submit" name="action" value="next">&nbsp;</button><br />
{% endif %}

{% if phase.can_cancel %}
  <button class="abort buttongradient" type="submit" name="action" value="cancel" tabindex="300">&times; Keskeytä</button>
{% else %}
  <button class="abort buttongradient btndisabled" type="submit" name="action" value="cancel" disabled="disabled">&times; Keskeytä</button>
{% endif %}

{% if phase.prev_phase %}
  <button class="buttongradient" type="submit" name="action" value="prev" tabindex="200">&laquo; Edellinen</button>
{% else %}
  <button class="buttongradient btndisabled" type="submit" name="action" value="prev" disabled="disabled">&laquo; Edellinen</button>
{% endif %}

{% if phase.payment_phase %}

  <button class="buttongradient" id="nextbutton" type="submit" formaction="https://payment.checkout.fi/" tabindex="100">{{ phase.next_text|safe }}</button>
{% elif phase.next_phase %}
  <button class="buttongradient" id="nextbutton" type="submit" name="action" value="next" tabindex="100">{{ phase.next_text|safe }}</button>
{% else %}
<button class="buttongradient btndisabled" type="submit" name="action" value="next" disabled="disabled">{{ phase.next_text|safe }}</button>
{% endif %}

ticket_sales/templates/ticket_sales/order_statement.html
{% comment %}
vim: shiftwidth=2 expandtab
encoding: utf-8
{% endcomment %}
<div id="left">
  <h2>Liput</h2>
	<div class="box">
  <ul>
    {% for product in products %}
      <li>
        {{ product.count }}&times; {{ product.product.name }} à {{ product.product.formatted_price }} = {{ product.formatted_price }}
      </li>
    {% endfor %}
      <li>Toimituskulut: {{ order.formatted_shipping_and_handling }}</li>
  </ul>

  <p><em>Yhteensä: {{ order.formatted_price }}</em></p>
  </div>
</div>

<h2>Toimitusosoite</h2>
<div class="box">
  <p>
    {{ order.customer.name }}<br/>
    {{ order.customer.address }}<br/>
    {{ order.customer.zip_code }} {{ order.customer.city }}
  </p>
  <p>
    {{ order.customer.email }}<br/>
    {{ order.customer.phone_number }}
  </p>
</div>

ticket_sales/templates/ticket_sales/thanks.html
{% extends "base/base.html" %}
{% load wizard_ui %}
{% comment %}
encoding: utf-8
vim: shiftwidth=2 expandtab
{% endcomment %}
{% block body_text %}
<h1>Kiitos tilauksesta!</h1>
<p>Tilauksesi on nyt valmis! Tilausvahvistus ja maksutiedot on lähetetty antamaasi sähköpostiosoitteeseen. Nähdään Traconissa!</p>
<p>Huomioithan, että lippuja toimitetaan pitkin kesää isommissa erissä, eli rannekeen toimituksessa voi kestää useampi viikko. Kaikki lipputilaukset toimitetaan kuitenkin <strong>hyvissä ajoin ennen tapahtumaa</strong>, eikä kukaan lippunsa ajoissa maksanut jää vaille lippuja.</p>
<p>Tilauksesi tiedot:</p>
{% endblock body_text %}
{% block form_content %}
{% include "ticket_sales/order_statement.html" %}
{% endblock form_content %}

ticket_sales/templates/ticket_sales/tickets.html
{% extends "base/base.html" %}
{% load wizard_ui %}
{% comment %}
encoding: utf-8
vim: shiftwidth=2 expandtab
{% endcomment %}
{% block body_text %}
<h1>Valitse ostettavat ennakkolippupaketit</h1>
{% endblock body_text %}
{% block form_content %}
<p>Kirjoita kenttiin, montako mitäkin tuotetta haluat. Voit tilata useita tuotteita samalla kertaa. Voit vielä tarkistaa tiedot myöhemmin, ennen kuin vahvistat tilauksen.</p>
<table>
  <tr>
    <th colspan="2">Tuote</th>
    <th class="right">Kappalehinta</th>
    <th class="input">Määrä</th>
  </tr>
  {% for iform in form %}
    <tr class="{{ iform.instance.product.classname }}{% if not iform.instance.product.in_stock %} loppuunmyyty{% endif %}">

      {% if iform.instance.product.image %}
        <td class="productimage"><img src="{{ MEDIA_URL }}/images/{{ iform.instance.product.image }}" alt="{{ iform.instance.product.name }}" /></td>
      {% else %}
        <td class="productimage"><img src="{{ MEDIA_URL }}/images/oletustuotekuva.png" alt="Ei tuotekuvaa" /></td>
      {% endif %}

      <td class="productname">{{ iform.instance.product.name }} <div class="description">{{ iform.instance.product.description }}</div>
        {% if iform.instance.product.in_stock %}
          {% if iform.instance.product.availability_low %}
            <div class="tuotesaldo">Saatavilla enää {{ iform.instance.product.amount_available }} kpl!</div>
          {% endif %}
        {% else %}
          <div class="loppuunmyyty">Loppuunmyyty!</div>
        {% endif %}
      </td>

      <td class="right">{{ iform.instance.product.formatted_price }}</td>

      {% if iform.instance.product.in_stock %}
        <td class="tcount">{{ iform.count }}</td>
      {% else %}
        <td class="tcount">&nbsp;</td>
      {% endif %}
    </tr>
  {% endfor %}
</table>
<p id="lisatietojalipuista"><a href="http://2012.tracon.fi/liput" target="_blank">Lisätietoja lipuista...</a></p>
{% endblock form_content %}
{% block mascot_text %}
{% endblock %}

ticket_sales/templates/ticket_sales/welcome.html
{% extends "base/base.jade" %}
{% load wizard_ui %}
{% comment %}
encoding: utf-8
vim: shiftwidth=2 expandtab
{% endcomment %}
{% block body_text %}
<h1>Tervetuloa varaamaan Tracon 7 -majoituspaikkoja!</h1>
{% endblock %}
{% block form_content %}
{% comment %}<p class="welcome">Tervetuloa Tracon 7:n ennakkolippukauppaan. Tästä verkkokaupasta voit ostaa itsellesi ja vaikka myös kavereillesi etukäteen liput ja majoitukset ensi kesän tapahtumaan. Liput Traconiin ovat myös harrastajalle oiva lahjaidea!</p>
<p class="welcome">Tuotteet maksetaan tilisiirrolla. Tilauksilla on maksuaikaa <strong>7 päivää tilauksesta</strong>.</p>
<p class="welcome">Lippuja toimitetaan pitkin kesää isommissa erissä, eli rannekeen toimituksessa voi kestää useampi viikko. Kaikki lipputilaukset toimitetaan kuitenkin <strong>hyvissä ajoin ennen tapahtumaa</strong>, eikä kukaan lippunsa ajoissa maksanut jää vaille lippuja.</p>
<p class="welcome">Ennakkolipunmyynti verkossa päättyy <strong>perjantaina 17. elokuuta</strong>.</p>
<p class="welcome">Lisätietoja lipuista voit lukea <a href="http://2012.tracon.fi/liput" target="_blank">tapahtuman kotisivuilta.</a></p>{% endcomment %}
<p class="welcome">Tracon-lippujen ennakkomyynti verkossa päättyi <strong>perjantaina 17. elokuuta</strong>. Majoituspaikkojen myynti verkossa päättyi <b>maanantaina 3. syyskuuta</b>.</p>
<p class="welcome">Lisätietoja lipuista voit lukea <a href="http://2012.tracon.fi/liput" target="_blank">tapahtuman kotisivuilta.</a></p>
{% endblock %}